# Generated by Django 3.2.2 on 2021-05-13 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernumber', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=10000)),
                ('password', models.CharField(max_length=10000)),
                ('link', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernumber', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('userPassword', models.CharField(max_length=500)),
            ],
        ),
    ]
